services:
    web:
        ports:
            - ${WEB_PORT}:8000
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - FRONT_URI=${FRONT_URI}
            - AUTHJWT_SECRET_KEY=${AUTHJWT_SECRET_KEY}
    db:
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - ${DB_PORT}