services:
    api:
        ports:
            - 8008:8000
        environment:
            - POSTGRES_URL=postgresql://m2_react:m2_react@db:5432/m2_react
            - CLIENT_URL=http://localhost:3000
            - AUTHJWT_SECRET_KEY=SECRET
    db:
        environment:
            - POSTGRES_USER=m2_react
            - POSTGRES_PASSWORD=m2_react
            - POSTGRES_DB=m2_react
        expose:
            - 5432