services:
    api:
        ports:
            - ${WEB_PORT}:8000
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - CLIENT_URL=${CLIENT_URI}
            - AUTHJWT_SECRET_KEY=${AUTHJWT_SECRET_KEY}
            - TELEGRAM_API_URL=${TELEGRAM_API_URL}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - TELEGRAM_CHANNEL_LINK=${TELEGRAM_CHANNEL_LINK}
    db_postgres:
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        expose:
            - ${DB_PORT}